#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["AggregateApp.csproj", "."]
COPY ["../Infrastructure/Infrastructure.csproj", "../Infrastructure/"]
COPY ["../Core/Core.csproj", "../Core/"]
RUN dotnet restore "./AggregateApp.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "AggregateApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "AggregateApp.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AggregateApp.dll"]
